---
openapi: 3.0.0
info:
   version: 1.3.0
   title: onetomany open api specification
   description: students API
   termsOfService: http://api_url/terms/
   contact:
      name: ContactName
      email: hello@wolox.co
      url: https://www.wolox.com.ar/
   license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
   - url: http://localhost:8030
     description: students
tags:
- name: studentsentity
  description: Second Entity
paths:
   "/studentsentity":
      get:
         tags:
         -  studentsentity
         description: GpGetAllValues
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
      post:
         tags:
         -  studentsentity
         description: GpCreate
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/studentsentity"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
   "/studentsentity/get/searchrelationship":
      get:
         tags:
         -  studentsentity
         description: GpSearchRelationship
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
components:
   schemas:
      studentsentity:
         type: object
         properties:
            name:
               type: "string"
               description: Description
            age:
               type: "number"
               description: Description
            subjectsid:
               type: "string"
               description: Description
            studentid:
               type: "number"
               description: Description